NKRO_ENABLE = no
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
UNICODE_ENABLE = yes
SEND_STRING_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
RGBLIGHT_ENABLE = yes

CAPS_WORD_ENABLE = yes
