EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
UNICODE_ENABLE = yes
SEND_STRING_ENABLE = yes
RGBLIGHT_ENABLE = yes
CAPS_WORD_ENABLE = yes
AUTOCORRECT_ENABLE = yes

NKRO_ENABLE = no
AUTO_SHIFT_ENABLE = no
